# NGINX and PHP FPM Services to test its configurations

version: "3.7"

services:

  nginx:

    build:
      context: .
      dockerfile: nginx/Dockerfile
    # naming during build
    image: skinny-hosts/core-nginx-web-server:${NGINX_WS_VERSION}
    tty: true
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_ROOT=${NGINX_ROOT}
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    command: bash -c 'wait4ports -q -t 60 -s 10 tcp://php:${PHP_PORT}; /docker-entrypoint.sh nginx -g "daemon off;"'

  php:
    image: ghcr.io/skinny-hosts/core-php-fpm-web-server:latest
    tty: true
    restart: always
    networks:
      - backend
    ports:
      - 9000
    volumes:
      - ./www:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - APP_ENVIROMENT=${APP_ENVIROMENT}
      - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

networks:

  backend:
    driver: bridge

volumes:

  dbdata:
    driver: local
    labels:
      sh.project.name: ${COMPOSE_PROJECT_NAME}